### ISSUE TITLE
Where should the UI appear and what should it look like?

### ISSUE THREAD

**Issue by janpio** [ameboide/diff-commits#1]
Hey, I'm one of the many watchers on that issue you commented with this link - super awesome if it would work.

I installed Tampermonkey and this userscript, but I couldn't find out where the alternative and additional UI on Bitbucket should appear. I was expecting it on the page of one commit, but no luck. Am I to blind?

**Comment by ameboide** [comment]
It should appear as a "D" button next to the links to commits, for example in the "Commits" tab of a pull request. Click on the button next to the first commit and then on the one for the last commit to see the comparison between those 2 (note that bitbucket sorts them newest to oldest while github is oldest to newest, the buttons should be pressed oldest first and newest later)

**Comment by janpio** [comment]
Hmm... should it work on https://github.com/ameboide/diff-commits/commits/master or https://bitbucket.org/atlassian/jira-dvcs-connector/pull-requests/127/add-analytics-to-smart-commits/commits?

**Comment by ameboide** [comment]
Both, though I just updated it for github because the site changed recently, so the new version should work on https://github.com/ameboide/diff-commits/commits/master

**Comment by janpio** [comment]
Hmm, nothing on both for me :/ What's the best way to debug this?

**Comment by ameboide** [comment]
If you were using Chrome, then the latest version should work
